INSERT INTO provincias (provincias) VALUES ( 'Araba/Álava');
INSERT INTO provincias (provincias) VALUES ('Albacete');
INSERT INTO provincias (provincias) VALUES ('Alicante/Alacant');
INSERT INTO provincias (provincias) VALUES ('Almería');
INSERT INTO provincias (provincias) VALUES ('Ávila');
INSERT INTO provincias (provincias) VALUES ('Badajoz');
INSERT INTO provincias (provincias) VALUES ('Balears, Illes');
INSERT INTO provincias (provincias) VALUES ('Barcelona');
INSERT INTO provincias (provincias) VALUES ('Burgos');
INSERT INTO provincias (provincias) VALUES ('Cáceres');
INSERT INTO provincias (provincias) VALUES ('Cádiz');
INSERT INTO provincias (provincias) VALUES ('Castellón/Castelló');
INSERT INTO provincias (provincias) VALUES ('Ciudad Real');
INSERT INTO provincias (provincias) VALUES ('Córdoba');
INSERT INTO provincias (provincias) VALUES ('Coruña, A');
INSERT INTO provincias (provincias) VALUES ('Cuenca');
INSERT INTO provincias (provincias) VALUES ('Girona');
INSERT INTO provincias (provincias) VALUES ('Granada');
INSERT INTO provincias (provincias) VALUES ('Guadalajara');
INSERT INTO provincias (provincias) VALUES ('Gipuzkoa');
INSERT INTO provincias (provincias) VALUES ('Huelva');
INSERT INTO provincias (provincias) VALUES ('Huesca');
INSERT INTO provincias (provincias) VALUES ('Jaén');
INSERT INTO provincias (provincias) VALUES ('León');
INSERT INTO provincias (provincias) VALUES ('Lleida');
INSERT INTO provincias (provincias) VALUES ('Rioja, La');
INSERT INTO provincias (provincias) VALUES ('Lugo');
INSERT INTO provincias (provincias) VALUES ('Madrid');
INSERT INTO provincias (provincias) VALUES ('Málaga');
INSERT INTO provincias (provincias) VALUES ('Murcia');
INSERT INTO provincias (provincias) VALUES ('Navarra');
INSERT INTO provincias (provincias) VALUES ('Ourense');
INSERT INTO provincias (provincias) VALUES ('Asturias');
INSERT INTO provincias (provincias) VALUES ('Palencia');
INSERT INTO provincias (provincias) VALUES ('Palmas, Las');
INSERT INTO provincias (provincias) VALUES ('Pontevedra');
INSERT INTO provincias (provincias) VALUES ('Salamanca');
INSERT INTO provincias (provincias) VALUES ('Santa Cruz de Tenerife');
INSERT INTO provincias (provincias) VALUES ('Cantabria');
INSERT INTO provincias (provincias) VALUES ('Segovia');
INSERT INTO provincias (provincias) VALUES ('Sevilla');
INSERT INTO provincias (provincias) VALUES ('Soria');
INSERT INTO provincias (provincias) VALUES ('Tarragona');
INSERT INTO provincias (provincias) VALUES ('Teruel');
INSERT INTO provincias (provincias) VALUES ('Toledo');
INSERT INTO provincias (provincias) VALUES ('Valencia/València');
INSERT INTO provincias (provincias) VALUES ('Valladolid');
INSERT INTO provincias (provincias) VALUES ('Bizkaia');
INSERT INTO provincias (provincias) VALUES ('Zamora');
INSERT INTO provincias (provincias) VALUES ('Zaragoza');
INSERT INTO provincias (provincias) VALUES ('Ceuta');
INSERT INTO provincias (provincias) VALUES ('Melilla');